name: GCP_test

on:
  push:
    branches: [ "master" ] #

jobs:
  upload-data:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: 'actions/checkout@v4'

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SA_EMAIL }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      #
      - name: 'Install Dependencies'
        run: |
          pip install google-cloud-storage

      #
      - name: 'Upload to GCS'
        env:
          GCP_BUCKET_NAME: 'ie7374-lab-data-${{ secrets.GCP_PROJECT_ID }}'
        run: |
          python GCP/Lab1/upload_to_gcs.py
          

      - name: 'List bucket contents'
        run: |
          gcloud storage ls --recursive gs://ie7374-lab-data-${{ secrets.GCP_PROJECT_ID }}/
          

      - name: 'Download from GCS'
        env:
          GCP_BUCKET_NAME: 'ie7374-lab-data-${{ secrets.GCP_PROJECT_ID }}'
        run: |
          python GCP/Lab1/download_from_gcs.py
          

      - name: 'Verify Local File'
        run: |
          echo "Checking data folder content..."
          ls -R data/