name: GCP_test

on:
  push:
    branches: [ "master" ] #

jobs:
  upload-data:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: 'actions/checkout@v4'

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SA_EMAIL }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      #
      - name: 'Install Dependencies'
        run: |
          pip install google-cloud-storage

      # æ–°å¢ï¼šæ‰§è¡Œä¸Šä¼ è„šæœ¬ ğŸš›
      - name: 'Upload to GCS'
        env:
          # å®šä¹‰å­˜å‚¨æ¡¶åç§°ï¼Œä½ å¯ä»¥è‡ªå·±å–ä¸ªåå­—
          GCP_BUCKET_NAME: 'ie7374-lab-data-${{ secrets.GCP_PROJECT_ID }}'
        run: |
        
          python GCP/Lab1/upload_to_gcs.py